version: '3'
services:
  backend:
    container_name: backend-blue
    image: publicdeveh/bitta-kotlin:latest
    ports:
      - "8081:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  backend_alternate:
    container_name: backend-green
    image: publicdeveh/bitta-kotlin:latest
    ports:
      - "8082:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod